export const BINGO_PHRASES: Record<number, string> = {
  "1": "Rezzekes op d'ieste plosj",
  "2": "Twie pagadders in ons hois",
  "3": "Droi raa oieren in e pènneke gekloesjt",
  "4": "Aagt a annen on ane gedong",
  "5": "A oeiren van anne kop zaugen",
  "6": "Ge moetj azoe den neldj nie oit hangen",
  "7": "'t Prinsjte polsjte",
  "8": "Giel den bataklang was mei",
  "9": "Metnienen doei a zjier",
  "10": "Tin,'k hem den boer zen slep gezing",
  "11": "Moakt a troiken isj nat, nimmero elef",
  "12": "On 't hoilig hert speltj nimmero twelef",
  "13": "Weir doeng voesj",
  "14": "Azoe een schoitkit",
  "15": "'k Zal a isj be anen schabernak pakken",
  "16": "Getz giene poeit om op te stoon",
  "17": "Noste weik is 't al nievejoorsauvend",
  "18": "'k Kroig er kiekevlies van!",
  "19": "Wa ne karottentrekker zedde goi zeg",
  "20": "'k Em flanellen bienen ",
  "21": "Gelek as'n on 't zwanzjelen is",
  "22": "E stik in a zjip emmen",
  "23": "'t Es va zjaloesderiederoi",
  "24": "Zetj da kindj mè zen gat oit de windj",
  "25": "As a broek mor waggelt",
  "26": "Dat es oeik een vrie",
  "27": "Onder a vois kroigen",
  "28": "Ier es een voil jeanet",
  "29": "Wè gon ons voesjdraugen",
  "30": "Ge zetj een verroibakkes",
  "31": "Meiren moen ek ni gon travakken",
  "32": "Hoe ne mensj van zijn roetjen kan zen",
  "33": "Da kaan der ni oon rieken",
  "34": "Ienen me e profoitig gezicht",
  "35": "Azoei ne pottepei",
  "36": "iemand ne poter schiljeren",
  "37": "'k Zal a isj poetjenlap doeng",
  "38": "Goed op a poeiten gevallen zen",
  "39": "Een voil plooster",
  "40": "Ziet da ge ni oitroist want 't zen dor plasjkoppen",
  "41": "'t Es van petjen ploei",
  "42": "Ne sjokolatten peimel",
  "43": "Azoei een pantomiene",
  "44": "Een ovventierent a nie",
  "45": "In 't joor nul as d'oilen preiken",
  "46": "In 't gat van de mert",
  "47": "Z'is oongetraad",
  "48": "Ben er nog ni oon of omtrent geweist",
  "49": "Ze woren aal overboeft",
  "50": "'t Er zal nog ewa oeverentweir geklapt werren",
  "51": "Zennen nest droin",
  "52": "Da zitj in zennen neis",
  "53": "Nemna!",
  "54": "Een floere moil",
  "55": "Ne roike mensj isj oordig",
  "56": "'t Es lepsaas",
  "57": "On 't ieste kraum meigde ni koeipen",
  "58": "Da werkt op men koeirekes",
  "59": "Ver 't land te kloeiten",
  "60": "Keskejevoe",
  "61": "'t Es pesies ienen vanachter den Hoiligeb Jowannes",
  "62": "Heer jongens zen thois",
  "63": "Lotj hem mor hoeben en toeben",
  "64": "Van 't alverdroi donker",
  "65": "En keê na groin wie da da was?",
  "66": "Bloift er mè a fikken af!",
  "67": "Zoe en zoe",
  "68": "Van de bolje in de zep gerauken",
  "69": "Een finne binnendoeng",
  "70": "Zennen ballong go ni op",
  "71": "Tobbelthoeip schoiten",
  "72": "Zu schief as een haaten hekken",
  "73": "Ge keje 't aal ni hemmen, een dikke vraa en veil plosj in a bedde",
  "74": "De groite zjaar oithangen",
  "75": "De leste zen de beste"
}
