export const BINGO_PHRASES: Record<number, string> = {
  1: "Moederziel alleen (maar ’t glas is vol)",
  2: "Het zwaantje, proper in z’n eentje",
  3: "Drie keer is scheepsrecht, jawadde",
  4: "Blijf zitten, ’t is hier beter",
  5: "Een handjevol, maar ’t kan tellen",
  6: "Ge weet wel… oei oei",
  7: "’t Zit snor",
  8: "De bril op, we zien het weer",
  9: "Gelijk ne kat met chance",
  10: "Schoon rond gelijk nen bal",
  11: "Het zottengetal",
  12: "Nen dozijn, gratis is dat ni",
  13: "Hout vasthouden en doorpakken",
  14: "Cruijff zou zeggen: simpel",
  15: "Een half ei en toch content",
  16: "Zoet zestien, vol streken",
  17: "Nog net geen pintje officieel",
  18: "Volwassen… op papier",
  19: "Just nog efkes",
  20: "Twee nullen, perfect voor sommige",
  21: "De sleutel van de deur… kwijt",
  22: "Twee zwaantjes in ’t water",
  23: "Schoon gescoord",
  24: "Een bak bier voor kerstavond",
  25: "Zilver, maar wij zijn goud",
  26: "Twee keer pech, oppassen",
  27: "Geluksgetal… voor wie gelooft",
  28: "Ne vette pad",
  29: "Bijna dertig, al content",
  30: "’t Leven begint pas",
  31: "Oliebollen in aantocht",
  32: "De tandarts lacht",
  33: "Dubbel chance",
  34: "Alles erop en eraan",
  35: "Half zeventig, caféwiskunde",
  36: "Drie dozijn, da’s ne hoop",
  37: "Nog jong van geest",
  38: "Midden in de nacht en wakker",
  39: "Ai ai ai…",
  40: "’t Begint pas",
  41: "Tijd voor leute",
  42: "Het antwoord op alles",
  43: "Beetje vreemd, maar ’t zal wel",
  44: "Volle bak",
  45: "Eerste helft, nog efkes",
  46: "Tussen wal en schip",
  47: "Waar blijft de schat?",
  48: "Een half pond, doe maar bij",
  49: "Bijna Abraham, pak nog ne koek",
  50: "Proficiat, ge zijt er geraakt",
  51: "Voorzichtig op de trap",
  52: "Altijd te weinig verlof",
  53: "De joker, da zijt gij",
  54: "Bel aan of zwijg",
  55: "High five!",
  56: "Was ’t maar waar…",
  57: "Ge moet het maar hebben",
  58: "Wij waken mee",
  59: "’t Laatste jaar van de zestig",
  60: "Tik tok, ’t gaat vooruit",
  61: "Nog goed bij de pinken",
  62: "Pensioen in zicht… of ni",
  63: "Hou u vast, ’t nadert",
  64: "Yeah yeah!",
  65: "Koffie met koek",
  66: "Duivels goed",
  67: "Stapje verder",
  68: "Laat u nie doen",
  69: "Omdraaien maar… en zwijgen",
  70: "Schoon meegedraaid",
  71: "In de wolken (van de cava)",
  72: "’t Past gelijk gegoten",
  73: "Hou vol, we zijn er bijna",
  74: "Nog eentje dan… allez",
  75: "’t Is gedaan — BINGO!"
}; 
