export const BINGO_PHRASES: Record<number, string> = {
  "1": "Alliejen (as e bieken)",
  "2": "Afgebèsteld en alliejen",
  "3": "Droi raa aaieren in e pènneke gekloesjt",
  "4": "Aagt a annen on a gedong",
  "5": "E stekske, mor 't kan tellen",
  "6": "E venoin... oei oei",
  "7": "'t Prinsjte polsjte",
  "8": "Eët gespannen? We zieng het weir",
  "9": "G'et chanse gelek ne kat",
  "10": "Schoon rond gelek nen ooibekken",
  "11": "'t Es iene va Lei",
  "12": "Nen dozijn, da kaan mennen broinen ni trekken",
  "13": "Weir doeng voesj",
  "14": "Simmen as nen eizel",
  "15": "Deltj, elk de helft en toch content",
  "16": "E bevallegort mé streken",
  "17": "Bekanst e stik in men zjilei",
  "18": "Volwassen... menne kop der af!",
  "19": "Bozjop, nog efkes",
  "20": "Twei nullen, 't husken ver sommegte",
  "21": "De sleutel van de deir... kwoit",
  "22": "Twei biejesten in den Denjer",
  "23": "Gralek guu gescoord!",
  "24": "Azoei nen doesj patatten ver de kestboeim",
  "25": "Gaad, mor weir zèn Oilsjteneers",
  "26": "Pastapora, ’t za stront regenen",
  "27": "Chanse... as ge’t betraan kunt",
  "28": "Ne vette djoeben",
  "29": "Bekanst dertig en goe geloin",
  "30": "Skaan, fistjen baan!",
  "31": "Meirbollen in den ovent",
  "32": "E bakkes om stront op te sorteiren",
  "33": "Dubbel chanse mé schoap",
  "34": "Aal drop en dran",
  "35": "Deltj kaffeiwiskunde",
  "36": "Azoei nen doesj, da’s ne hoop",
  "37": "Nog foin van giejst",
  "38": "In de joren loekes 's meires wakker",
  "39": "Lap... ai ai ai",
  "40": "Aroet! ’t Begint pas",
  "41": "Toit ver leute",
  "42": "'t Antwoord op aal",
  "43": "Ewa loesj, mor 't zalwel a'a skaan",
  "44": "Keirre goe vol",
  "45": "Deltj, nog efkes voesjdoeng",
  "46": "In 't gat van de mert",
  "47": "Woor zitj a mokke?",
  "48": "E betjen greimelken derboi",
  "49": "Bekanst Abraham, eet nog e booken",
  "50": "En zè mor gerest, ge zetj er",
  "51": "Past op de trappekes!",
  "52": "Altet te weineg konzjei",
  "53": "De djoeben, da zetj goi",
  "54": "Aagt a moil of beltj",
  "55": "Plasjt insj in eir annen!",
  "56": "Da za teigen à jaket zèn",
  "57": "Ge moet et mor emmen",
  "58": "Weir waken méé en wees mor gerest",
  "59": "'t Enjevan de zestig",
  "60": "Affeseren, 't goat veiroit!",
  "61": "Nog baa de pinken, menne kop der af!",
  "62": "Ne verloeren dag in zicht",
  "63": "Aagt a annen on a gedong, ’t komt",
  "64": "Wéé baa toet jong!",
  "65": "E zjat kaffe mé e booken",
  "66": "Doeivels guu",
  "67": "Stapje voesj",
  "68": "Lotj a eige ni doeng!",
  "69": "Auverecht en aagt a moil",
  "70": "Schoon meigedoeng in de joren loekes",
  "71": "In de wolken va de chaneivel",
  "72": "'t Past gelek gegoten mé schoap",
  "73": "Possensje, we zèn der bekanst",
  "74": "Nog iéën... aroet!",
  "75": "'t Es afgezing — BINGO!"
}
